// 自动生成: data/cities/*.json -> src/cities.js (勿手改)
export const CITIES = [
  {
    "name": "北京",
    "pinyin": "beijing",
    "tier": "一线",
    "avg_salary_yearly_wan": 23.27,
    "job_density_index": 98,
    "key_industries": [
      "信息技术/互联网/AI大模型",
      "金融",
      "科技服务/总部经济",
      "医药健康",
      "集成电路/智能制造",
      "文化创意"
    ],
    "avg_price_per_sqm": 48521,
    "price_to_income_ratio": 18.8,
    "downpayment_median_wan": 65.5,
    "purchase_restrictions_text": "京籍家庭限购2套；非京籍家庭社保/个税连续缴纳满1年，五环内限购1套（多子女家庭可+1套），五环外不限套数；通州执行与全市统一政策（原双限购已取消）",
    "mortgage_rate_first": 3.05,
    "hukou_difficulty_score": 95,
    "social_security_years_required": 7,
    "pension_base_lower": 7270,
    "maternity_leave_days": 158,
    "region": "华北",
    "avg_commute_minutes": 47,
    "tier3_hospitals": 81,
    "aqi_good_days_ratio": 85.2,
    "climate_summary": "温带半湿润大陆性季风：四季分明，冬冷（-5~5℃）有暖气，夏热（28-35℃），春秋短；春季偶有沙尘，冬季偶有雾霾（近年显著改善）；年日照约2600小时",
    "cultural_facilities_index": 98,
    "education_resources": "985×8（清北人师航理农中民族）+211×26；基础教育：人大附/清华附/北京四中/十一学校等全国顶尖；海淀黄庄为全国教培中心，学区竞争激烈度全国第一",
    "talent_policy_note": "分区补贴（示例海淀区2026新政）：经认定重点产业体系内用人单位应届毕业生可申领 1000元/月×最长2年安居补贴；海淀北部四镇额外+500元/月安居奖励；未叠加其他住房保障",
    "rent_subsidy_note": "各区差异化：海淀『海青安居』1000元/月×2年（北部+500）；朝阳/丰台/经开区均有区级人才租房补贴，金额500-3000元/月不等；需区重点企业就业+在京无房"
  },
  {
    "name": "长沙",
    "pinyin": "changsha",
    "tier": "新一线",
    "avg_salary_yearly_wan": 13.1,
    "job_density_index": 65,
    "key_industries": [
      "工程机械（三一重工/中联重科/山河智能）",
      "新材料",
      "汽车与新能源汽车（比亚迪等）",
      "电子信息/音视频装备（马栏山视频文创园）",
      "文化创意与新媒体（芒果TV/茶饮新消费）"
    ],
    "avg_price_per_sqm": 9653,
    "price_to_income_ratio": 6.6,
    "downpayment_median_wan": 13,
    "purchase_restrictions_text": "2024-04-18 起全面取消限购（长沙市住建局《关于支持居民购买改善住房的通知》：全市买房不再审查购房者资格、不限套数，执行7年的限购正式退出）；「以旧换新」按认房不认贷享首套优惠",
    "mortgage_rate_first": 3.05,
    "hukou_difficulty_score": 15,
    "social_security_years_required": 0,
    "pension_base_lower": 4106,
    "maternity_leave_days": 158,
    "region": "华中",
    "avg_commute_minutes": 34,
    "tier3_hospitals": 33,
    "aqi_good_days_ratio": 87.4,
    "climate_summary": "亚热带季风湿润气候：夏季酷热漫长（「四大火炉」之一，7-8月常35℃+）、冬季湿冷（1月均温约5℃）、春秋短促；年降水约1400mm、雨日多（近一年统计降雨109天）、日照偏少，冬春偶有雾霾（近一年霾",
    "cultural_facilities_index": 88,
    "education_resources": "985×3（中南大学、湖南大学、国防科技大学）+211×1（湖南师范大学；三所985同属211）；基础教育「四大名校」（长郡、雅礼、师大附中、长沙一中）竞赛实力全国知名；全市普通高校58所、在学研究生9.93万人（2025年末）",
    "talent_policy_note": "青年人才租房和生活补贴（35周岁及以下、毕业2年内、落户并在长工作，发放2年）：全日制本科6000元/年×2年=1.2万、硕士1万/年×2年=2万、博士1.5万/年×2年=3万、境外高校博士10万；另首次购房补贴：博士10万、硕士3万",
    "rent_subsidy_note": "青年人才安居工程：103个人才公寓项目、34168套房源（2025-09起陆续开放），符合条件可享「满6免1」租金优惠；2026年「才寓星程」人才保障房520套，符合条件免租金"
  },
  {
    "name": "成都",
    "pinyin": "chengdu",
    "tier": "新一线",
    "avg_salary_yearly_wan": 13.19,
    "job_density_index": 78,
    "key_industries": [
      "电子信息",
      "装备制造",
      "医药健康",
      "新型材料",
      "绿色食品",
      "数字经济/游戏电竞"
    ],
    "avg_price_per_sqm": 15866,
    "price_to_income_ratio": 10.8,
    "downpayment_median_wan": 21.4,
    "purchase_restrictions_text": "2024-04-29 起全市取消限购，不限套数、不审资格；限售分批放开中（2024-10-15 后购房取证即可交易）",
    "mortgage_rate_first": 3,
    "hukou_difficulty_score": 25,
    "social_security_years_required": 3,
    "pension_base_lower": 4699,
    "maternity_leave_days": 158,
    "region": "西南",
    "avg_commute_minutes": 38,
    "tier3_hospitals": 61,
    "aqi_good_days_ratio": 80.8,
    "climate_summary": "亚热带湿润：冬暖（均温5-8℃）夏热（28-33℃）多阴天少日照，年日照约1000小时全国偏低，冬有雾霾风险",
    "cultural_facilities_index": 85,
    "education_resources": "985×2（川大、电子科大）+211×3（西南交大、西南财大、川农）；基础教育有成都七中等全国名校，但学区竞争中等偏上",
    "talent_policy_note": "分区补贴：如青羊区一次性租房补贴 博士3万/硕士1.2万/本科0.6万（需符合区主导产业目录+3年合同+社保半年）",
    "rent_subsidy_note": "人才优租行动（2026-04 起）：A/B类100%、C类70%、D/E类50%租金补贴，上限50m²，累计≤36个月"
  },
  {
    "name": "广州",
    "pinyin": "guangzhou",
    "tier": "一线",
    "avg_salary_yearly_wan": 16.68,
    "job_density_index": 92,
    "key_industries": [
      "智能网联和新能源汽车",
      "数字经济/电子信息",
      "绿色石化和新材料",
      "生物医药与健康",
      "现代高端装备",
      "商贸会展/跨境电商"
    ],
    "avg_price_per_sqm": 37120,
    "price_to_income_ratio": 20,
    "downpayment_median_wan": 50.1,
    "purchase_restrictions_text": "2024-09-30 起全面取消限购，一线城市中率先全面放开：户籍/非户籍/单身人士在全市范围内购房不再审核资格、不限套数",
    "mortgage_rate_first": 3,
    "hukou_difficulty_score": 35,
    "social_security_years_required": 4,
    "pension_base_lower": 5510,
    "maternity_leave_days": 178,
    "region": "华南",
    "avg_commute_minutes": 37,
    "tier3_hospitals": 53,
    "aqi_good_days_ratio": 93.4,
    "climate_summary": "南亚热带季风：长夏短冬，年均温21-23℃，夏季湿热（28-35℃+高湿），冬季温和（10-18℃），回南天3-4月湿度高，年降水量1700mm+，台风季7-9月，无供暖需求",
    "cultural_facilities_index": 88,
    "education_resources": "985×2（中山大学、华南理工）+211×2（暨南大学、华南师大）；基础教育有华附、执信、广雅、省实等名校，学区竞争中等；K12国际化学校密度华南第一",
    "talent_policy_note": "市级无统一补贴，分区执行：① 南沙区吸纳应届生就业补贴 1000元/人/月×6月（给单位）+ B-1/2/3 人才卡应届生入住人才公寓租金优惠比例提至100% ② 黄埔区人才房票 本科10万/硕士15万/博士25万/博士后30万（购房补贴，2026-07-07 起受理）",
    "rent_subsidy_note": "分区执行：① 黄埔区人才住房租金补贴 最高2500元/月×5年（人才自住）、1500元/月×5年（人才父母）② 南沙区人才公寓A/B卡按市场评估价50%租金优惠、最长3年，应届生B卡首年100%优惠"
  },
  {
    "name": "杭州",
    "pinyin": "hangzhou",
    "tier": "新一线",
    "avg_salary_yearly_wan": 16.86,
    "job_density_index": 83,
    "key_industries": [
      "数字经济（电商/云计算/AI）",
      "视觉智能（数字安防）",
      "集成电路",
      "生物医药",
      "高端装备",
      "新能源汽车"
    ],
    "avg_price_per_sqm": 29222,
    "price_to_income_ratio": 15.6,
    "downpayment_median_wan": 39.4,
    "purchase_restrictions_text": "2024-05-09 起全市全面取消限购（不再审核购房资格，不限套数）；购房即可申请落户（取得合法产权住房的非本市户籍人员可申请落户）；新房限价已全面放开",
    "mortgage_rate_first": 3.05,
    "hukou_difficulty_score": 30,
    "social_security_years_required": null,
    "pension_base_lower": 5346,
    "maternity_leave_days": 158,
    "region": "华东",
    "avg_commute_minutes": 34,
    "tier3_hospitals": 26,
    "aqi_good_days_ratio": 85.8,
    "climate_summary": "亚热带季风：夏热冬冷（2025年市区年均气温19.6℃），6月梅雨、夏有酷暑（极端可达40℃），冬湿冷偶有霾，年降水1536mm、空气优良率85.8%",
    "cultural_facilities_index": 87,
    "education_resources": "985×1（浙江大学，一校独大）+无其他211；普通高校40所、在校生64.5万（研究生13.6万）；基础教育有杭州二中、学军中学等全国名校，学区竞争激烈",
    "talent_policy_note": "应届毕业生生活补贴：本科1万元、硕士3万元、博士10万元（2021-10-14前毕业博士5万），分两笔发放各50%；在富阳/临安/桐庐/淳安/建德等西部区县工作满3年再发相同额度一份；符合条件的非全日制研究生同等享受",
    "rent_subsidy_note": "新引进应届大学生租房补贴：本科及以上、在杭无房，每户每年1万元、可发3年；期满后收入低于城镇居民人均可支配收入的可续享，最长再3年（合计上限6年）；每年分两笔各50%发放"
  },
  {
    "name": "上海",
    "pinyin": "shanghai",
    "tier": "一线",
    "avg_salary_yearly_wan": 23.96,
    "job_density_index": 95,
    "key_industries": [
      "集成电路",
      "生物医药",
      "人工智能",
      "金融",
      "高端装备/船舶/汽车",
      "信息服务/软件"
    ],
    "avg_price_per_sqm": 59139,
    "price_to_income_ratio": 22.2,
    "downpayment_median_wan": 79.8,
    "purchase_restrictions_text": "2026-02-26 起大幅松绑：① 非沪籍连续缴纳社保/个税满1年即可购房（外环外不限套数，外环内限购1套）；② 连续缴纳满3年及以上，外环内限购2套；③ 持《上海市居住证》满5年及以上，全市限购1套，无需社保/个税证明。沪籍家庭按原政策执行。",
    "mortgage_rate_first": 3.05,
    "hukou_difficulty_score": 85,
    "social_security_years_required": 7,
    "pension_base_lower": 7546,
    "maternity_leave_days": 158,
    "region": "华东",
    "avg_commute_minutes": 36,
    "tier3_hospitals": 44,
    "aqi_good_days_ratio": 88.5,
    "climate_summary": "亚热带季风：四季分明，冬湿冷（均温3-8℃）夏闷热（28-35℃），梅雨季6-7月，台风季7-9月，年日照约1800小时，空气质量优良",
    "cultural_facilities_index": 90,
    "education_resources": "985×4（复旦、交大、同济、华师大）+211×10（含上财、上外、华东理工、东华、上大、上中医、海军军医大学等）；基础教育有上海中学、华二附中、复旦附中、交大附中等全国顶尖名校，学区竞争激烈",
    "talent_policy_note": "无全市统一应届生现金补贴；部分区有租房/安居补贴（如普陀/闵行/静安/虹口等新就业青年租房补贴：高水平大学本科以上、毕业3年内、35岁以下、社保基数≤2倍社平，第一年补贴40%-60%租金、最高2500元/月，第二年退坡50%）",
    "rent_subsidy_note": "新就业青年租房补贴（2026 起各区陆续推出）：高水平大学本科及以上、毕业3年内、35岁以下、在沪无房、社保基数≤2倍社平，租住保障性租赁住房可享第一年40%-60%租金补贴（外环内最高2500元/月、外郊环2000元/月、郊环外1500元"
  },
  {
    "name": "深圳",
    "pinyin": "shenzhen",
    "tier": "一线",
    "avg_salary_yearly_wan": 19.14,
    "job_density_index": 100,
    "key_industries": [
      "电子信息/通信设备",
      "互联网/软件信息服务",
      "先进制造/装备制造（机器人、无人机）",
      "金融服务",
      "新能源/新能源汽车",
      "生物医药/医疗器械"
    ],
    "avg_price_per_sqm": 55083,
    "price_to_income_ratio": 25.9,
    "downpayment_median_wan": 74.4,
    "purchase_restrictions_text": "未全面放开但大幅放宽（2026-04-30 新政）：福田/南山/宝安新安街道——深户家庭可购3套、非深户连续1年社保/个税可购2套、持深圳居住证的非深户家庭无需社保即可购1套；其他区域维持原有限购（深户2套、非深户1年社保1套）",
    "mortgage_rate_first": 3.05,
    "hukou_difficulty_score": 20,
    "social_security_years_required": 1,
    "pension_base_lower": 4775,
    "maternity_leave_days": 178,
    "region": "华南",
    "avg_commute_minutes": 35,
    "tier3_hospitals": 33,
    "aqi_good_days_ratio": 97.5,
    "climate_summary": "南亚热带海洋性季风气候：长夏短冬（夏季6-7个月、均温28-32℃，冬季温暖均温15-20℃基本无严寒），年均温约23℃，回南天潮湿，夏秋季有台风风险，年日照约1900小时",
    "cultural_facilities_index": 88,
    "education_resources": "本土无985/211（靠哈工大深圳、中大深圳、港中深等异地校区补充）；双一流1所（南方科技大学·数学）+深圳大学快速崛起；基础教育学位紧张、中考升学竞争激烈，基础教育是主要短板",
    "talent_policy_note": "2026-01-01 起青年人才新政：新引进优秀青年人才入户补贴——博士10万/硕士最高5万/本科最高3万（45岁以下、首次在深就业创业并缴社保，'秒批'入户）；另有免费短期住宿（面试/实习最长15天）",
    "rent_subsidy_note": "经认定青年人才未住过渡房可领安居补贴 1250元/月（税后1000），最长24个月；原'新引进人才租房和生活补贴'（本科1.5万/硕士2.5万/博士3万）已被2026新政取代，另设新引进博士人才生活补贴10万（35岁以下）"
  },
  {
    "name": "武汉",
    "pinyin": "wuhan",
    "tier": "新一线",
    "avg_salary_yearly_wan": 11.71,
    "job_density_index": 72,
    "key_industries": [
      "光电子信息",
      "汽车及零部件（新能源转型）",
      "生物医药与大健康",
      "高端装备制造",
      "航空航天",
      "网络安全（存储芯片）"
    ],
    "avg_price_per_sqm": 15336,
    "price_to_income_ratio": 11.8,
    "downpayment_median_wan": 20.8,
    "purchase_restrictions_text": "2023-09-19 起全面取消限购（二环线以内区域移出限购范围），不限套数、不审购房资格",
    "mortgage_rate_first": 3.05,
    "hukou_difficulty_score": 22,
    "social_security_years_required": 0,
    "pension_base_lower": 4498,
    "maternity_leave_days": 158,
    "region": "华中",
    "avg_commute_minutes": 37,
    "tier3_hospitals": 61,
    "aqi_good_days_ratio": 85.8,
    "climate_summary": "亚热带季风性湿润：夏季酷热漫长（7-8月常超35℃，传统『火炉』城市）、冬季湿冷（1月均温约3-5℃、无集中供暖）、梅雨季长（6月）、春秋短促；年降水量约1200mm",
    "cultural_facilities_index": 82,
    "education_resources": "985×2（武大、华科）+211×7所（武大、华科、地大(武汉)、武汉理工、华中农大、华中师大、中南财经政法）；在校大学生超140万（本专科121.87万+研究生22.53万，2025统计公报），全国三大智力密集区之一；基础教育有华师一附中",
    "talent_policy_note": "市级无普适现金补贴（以人才租赁房免租为主）；困难毕业生一次性求职补贴（低保/零就业/助学贷款等群体，武汉人社按湖北标准发放）；部分区有现金补贴：如青山区大学生一次性租房补贴2000元/人",
    "rent_subsidy_note": "人才租赁房租金减免：全日制大专以上、毕业6年内、在汉就业创业缴社保、家庭在汉无房→按不高于市场租金70%缴租，累计减免≤3年；博士免2年租金（上限2000元/月）、硕士免1年（上限1500元/月）"
  }
];
